print("Paso 1: Preparación")
print("- Reunir los materiales necesarios: una escoba, un alza basura para recoger el polvo y una bolsa de basura.")
print("- Asegúrse de que la habitación esté despejada de objetos grandes en el suelo para facilitar el barrido.")
print()
print("Paso 2: Agarrar la Escoba")
print("- Tomar la escoba por el mango con una mano y asegúrarse de que esté firme y no sueltar el polvo u otras basuras.")
print()
print("Paso 3: Planificación")
print("- Identificar el área que se va a barrer y decidir por dónde comenzar. Es recomendable empezar desde el fondo de la habitación y barrer hacia la puerta para no pisar el área ya limpia.")
print()
print("Paso 4: Barrido")
print("- Comenzae a barrer desde la esquina más alejada de la puerta.")
print("- Con movimientos firmes y controlados, empuja la suciedad y el polvo hacia el centro de la habitación.")
print("- Asegúrarse de barrer en todas las direcciones para recoger la mayor cantidad de suciedad posible.")
print()
print("Paso 5: Recoger el Polvo")
print("- Una vez que hayas barrido una sección, utiliza la pala para recoger el polvo y la suciedad acumulada en el centro de la habitación.")
print("- Levanta con el alza basura con cuidado la basura para evitar que el polvo se esparza nuevamente por el suelo.")
print()
print("Paso 6: Disposición de la Basura")
print("- Vacíar el alza basura en la bolsa de basura.")
print("- Si encuentras objetos grandes mientras barres, recógelos y colócalos en su lugar correspondiente en lugar de desecharlos.")
print()
print("Paso 7: Finalización")
print("- Continúar barriendo y recogiendo el polvo hasta que hayas cubierto toda la habitación.")
print("- Prestar atención a las esquinas y debajo de los muebles donde puede acumularse más polvo.")
print("- Una vez que hayas terminado, cierra la bolsa de basura y deséchala en el contenedor de basura correspondiente.")