print("Persona 1: ¡Qué tal, hermano! ¿Cómo andas?")
print("Persona 2: ¡Hola, pana! Tranqui, ¿vos?")
print("Persona 1: Bien, bien, aquí dándole nomás. ¿Has sentido el calor que hace hoy?")
print("Persona 2: ¡Sí, hermano! El sol está a full. ¿Probaste alguna comida rica últimamente?")
print("Persona 1: Anoche me mandé unas salteñas que estaban de rechupete. ¿Y tú?")
print("Persona 2: Uy, me comí un silpancho que me dejó lleno hasta las orejas.")
print("Persona 1: ¡Qué rico! Hablando de otra cosa, ¿cómo va el laburo?")
print("Persona 2: Con mil cosas, hermano. ¿Y tú?")
print("Persona 1: Igual, ajetreado. ¿Y las finanzas cómo van?")
print("Persona 2: Tratando de no gastar de más, ¿vos?")
print("Persona 1: Exacto, ahorrando lo que se puede. Bueno, me pego el paso. ¡Nos vemos!")
print("Persona 2: ¡Claro, brooo! ¡Nos vemos luego!")
